# this stage is run before uat-stage and production stage
# in an acceptance environment.
#
# 1. pass input env var
#
# 2. trigger Release System on this environment
#    Release External System Stubs (this is a placeholder step, no actions at the moment)
#    Checkout System Test Repository
#    Run Smoke Tests
#    Run Acceptance Tests
# 3. Tag the

# todo : move to test repo
name: Run Acceptance Stage

on:
  schedule:
    - cron: "0 6,18 * * 1-5"
  workflow_dispatch:

jobs:
  run-deploy-in-environment:
    uses: ./.github/workflows/release-stage.yml
    secrets: inherit
    with:
      EB_APP_FE: ${{ vars.EB_APP_FE }}
      EB_APP_BE: ${{ vars.EB_APP_BE }}
      EB_ENV_FE: ${{ vars.EB_ENV_ACCEPTANCE_FE }}
      EB_ENV_BE: ${{ vars.EB_ENV_ACCEPTANCE_BE }}

  # todo : release external system stub
  # todo : if want to reuse this workflow : have a check to release external system test instances in case of E2e env
  run-smoke-test:
    needs:
      - run-deploy-in-environment
    uses: 3T-Operations-Team/desk-bookings-system-tests/.github/workflows/smoke-test-on-host.yml@main
    with:
      EB_ENV: ${{ vars.EB_ENV_ACCEPTANCE_FE }}
    secrets: inherit

  run-acceptance-test:
    needs:
      - run-smoke-test
    uses: 3T-Operations-Team/desk-bookings-system-tests/.github/workflows/acceptance-test-on-host.yml@main
    with:
      EB_ENV: ${{ vars.EB_ENV_ACCEPTANCE_FE }}
    secrets: inherit

  on-acceptance-success:
    needs:
      - run-acceptance-test
    uses: 3T-Operations-Team/desk-bookings-fe/.github/workflows/update-tag.yml@main
    with:
      image_tag: latest
      new_tag: accept
    secrets: inherit
