# release stage to handle all services release candidates and
# run the system level tests based on the environment.
# for production and uat to build, this should pass.

name: Release Stage
on:
  workflow_call:
    inputs:
      EB_APP_FE:
        type: string
        required: true
      EB_APP_BE:
        type: string
        required: true
      EB_ENV_FE:
        type: string
        required: true
      EB_ENV_BE:
        type: string
        required: true
      TAG:
        type: string
        required: true
        default: latest

jobs:
  # TODO : add environment here?
  run-backend-deploy:
    uses: 3T-Operations-Team/desk-bookings-be/.github/workflows/deploy.yml@master
    secrets: inherit
    with:
      EB_ENVIRONMENT: ${{ inputs.EB_ENV_BE }}
      EB_APP: ${{ inputs.EB_APP_BE }}
      IMAGE_PATH: ${{ vars.IMAGE_PATH_BE }}:${{ inputs.TAG }}

  run-frontend-deploy:
    needs: run-backend-deploy
    uses: 3T-Operations-Team/desk-bookings-fe/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      EB_ENVIRONMENT: ${{ inputs.EB_ENV_FE }}
      EB_APP: ${{ inputs.EB_APP_FE }}
      IMAGE_PATH: ${{ vars.IMAGE_PATH_FE }}:${{ inputs.TAG }}
