name: Run UAT Stage

on:
  workflow_dispatch:

jobs:
  run-uat-deploy:
    uses: ./.github/workflows/release-stage.yml
    secrets: inherit
    with:
      EB_APP_BE: ${{ vars.EB_APP_BE }}
      EB_APP_FE: ${{ vars.EB_APP_FE }}
      EB_ENV_FE: ${{ vars.EB_ENV_UAT_FE }}
      EB_ENV_BE: ${{ vars.EB_ENV_UAT_BE }}
      TAG: 'draft'

  # presume that some test are run from manual testing and approve a tag
  approve-pre-release-tag-be:
    needs:
      - run-uat-deploy
    uses: 3T-Operations-Team/desk-bookings-system-tests/.github/workflows/update-tag.yml@main
    with:
      image-tag: draft
      new-tag: pre-release
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-be
    secrets: inherit
  approve-pre-release-tag-fe:
    needs:
      - run-uat-deploy
    uses: 3T-Operations-Team/desk-bookings-system-tests/.github/workflows/update-tag.yml@main
    with:
      image-tag: draft
      new-tag: pre-release
      IMAGE_NAME: ghcr.io/3t-operations-team/desk-bookings-fe
    secrets: inherit