name: Run UAT Stage

on:
  #todo : make it a cron job that runs every n hours
  workflow_dispatch:

jobs:
  # todo : pick up an acceptance related tag before processing for uat?
  # if it is not available then acceptance is not yet available.
  run-uat-deploy:
    uses: ./.github/workflows/release-stage.yml
    secrets: inherit
    with:
      EB_APP_BE: ${{ vars.EB_APP_BE }}
      EB_APP_FE: ${{ vars.EB_APP_FE }}
      EB_ENV_FE: ${{ vars.EB_ENV_UAT_FE }}
      EB_ENV_BE: ${{ vars.EB_ENV_UAT_BE }}
      TAG: 'draft'
